%% Submissions for peer-review must enable line-numbering
%% using the lineno option in the \documentclass command.
%%
%% Preprints and camera-ready submissions do not need
%% line numbers, and should have this option removed.
%%
%% Please note that the line numbering option requires
%% version 1.1 or newer of the wlpeerj.cls file, and
%% the corresponding author info requires v1.2

\documentclass[fleqn,10pt,lineno]{wlpeerj} % for journal submissions

% ZNK -- Adding headers for pandoc

\setlength{\emergencystretch}{3em}
\providecommand{\tightlist}{
\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{lipsum}
\usepackage[unicode=true]{hyperref}
\usepackage{longtable}


% Pandoc syntax highlighting
% See https://github.com/rstudio/rticles/issues/182

% Pandoc citation processing
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc} % for calculating minipage widths
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

% Pandoc Header

\title{Draft: Spanish Flu Mortality}

\author[]{Jonathan Jayes}




%
% \author[1]{First Author}
% \author[2]{Second Author}
% \affil[1]{Address of first author}
% \affil[2]{Address of second author}
% \corrauthor[1]{First Author}{f.author@email.com}

% 

\begin{abstract}

% Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text.
\end{abstract}

\begin{document}

\flushbottom
\maketitle
\thispagestyle{empty}

\hypertarget{the-1918-spanish-flu-pandemic-in-south-africa-assesing-mortality}{%
\section{The 1918 Spanish flu pandemic in South Africa: assesing mortality}\label{the-1918-spanish-flu-pandemic-in-south-africa-assesing-mortality}}

\hypertarget{abstract}{%
\subsection{Abstract}\label{abstract}}

This paper looks at mortality during the Spanish flu pandemic of 1918 in 15 districts in the Cape Province of South Africa.

40,000 death notices.

\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

I assess excess mortality using three different methods to quantify how many people died in each district.

Then I look at three measures of pre-pandemic health and how these correlate with excess mortality.

\hypertarget{historical-background}{%
\subsection{Historical background}\label{historical-background}}

\hypertarget{importance-of-initial-exposure}{%
\paragraph{Importance of initial exposure}\label{importance-of-initial-exposure}}

\hypertarget{findings-in-other-literature}{%
\subsection{Findings in other literature}\label{findings-in-other-literature}}

\hypertarget{data}{%
\subsection{Data}\label{data}}

Forms of Information of a Death. As of Act No.~7 of 1894 of the Cape Colony.

``N.B. -- If the certificate of a Medical Practitioner is produced, the causes of Death and Duration of Illness must be recorded in the Registration Book by the Deputy Registrar and Assistant to the Deputy Registrar as stated in such Certificate, which is to be attached to the form.''

\hypertarget{classification-of-race-from-ethnicity}{%
\subsubsection{Classification of race from ethnicity}\label{classification-of-race-from-ethnicity}}

Race is one important feature of the analysis. As noted in Fourie and Jayes (2021), health and wealth in the Cape Province of 1918 were ``closely correlated to race\ldots{} with race being a strong predictor of income and social status'' (Fourie and Jayes 2021, 2). The death notices provide a field for the race of the deceased to be recorded. However, often ethnicity of the deceased was recorded instead. See for example the record of Wills Bunu, who died in Queenstown on the 26th of October 1918 whose race is recorded as ``Fingo.'' Fingo is a term for a group of ethnicities who fled Natal in the aftermath of the \emph{Mfecane} to reside in the Xhosa speaking Eastern region of the Cape (Stapleton 1995, 362). Mtumane (2017) argues that the Fingo were ``were embraced and integrated'' by Xhosa in the Eastern Cape by the time of the Spanish flu (Mtumane 2017, 68).

\begin{figure}
\centering
\includegraphics{images/wills_bunu.jpg}
\caption{Form of Information of the death of Wills Bunu}
\end{figure}

Further, more than 200 ethnicities appear only once among the records, such that the distribution of observed ethnicities is skewed to the right, with 419 \emph{different} ethnicities recorded.

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-2-1.pdf}

In order to classify these 419 different categorical values down into a more manageable number; 3 broad race groupings in use in the Cape at the time and in South Africa today, I use a combination of regular expression and a linear support vector machine learning algorithm.

\hypertarget{machine-learning-model-specification}{%
\paragraph{Machine learning model specification}\label{machine-learning-model-specification}}

In order to simplify the problem I hand coded the minority class (white) using regular expression (for example, coding ``European'' and ``English'' to white), and used a linear support vector machine to classify the remaining observations to black and coloured based on a hand-coded training set. Suthaharan (2016) explains that a linear support vector machine is well suited to binary text classification, as it can make use of sub-word features in a computationally cheap manner. It performs best when the classes in the training set are balanced. Because white individuals make up a minority of the dataset, it is possible to simply hand-code their observations as white and then make use of the machine learning algorithm to classify the remaining roughly equal classes. The binary linear SVM works by dividing the data domain along a hyperplane ``to separate classes in the original domain'' (Suthaharan 2016, 2).

The advantage of the linear SVM as opposed to a more flexible machine learning method, for example a neural network, is that the linear SVM is explainable and it is possible to pull out indicators of how the algorithm performs the classification. In this case, I use the sub-word features of the ethnicities as predictors of race.

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-3-1.pdf}

\hypertarget{how-many-died-during-the-pandemic}{%
\subsection{How many died during the pandemic?}\label{how-many-died-during-the-pandemic}}

Figure \ref{fig:viridis-deaths} shows a heatmap of the deaths.

\begin{figure}
\centering
\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/viridis-deaths-1.pdf}
\caption{\label{fig:viridis-deaths}Heatmap of deaths per week}
\end{figure}

There is considerable variation in the crude death rate by district over time, as shown in Figure \ref{fig:town-density}. Here we can see two important features of the pandemic in our sample of Cape districts. First, the pandemic arrived in different districts at different times. In districts close to Cape Town, where the soldiers arrived soon after they were released from quarantine at port.

{[}Cite Philips here with the history of the arrival of the ships from Freetown{]}

Crude death rate is the total number of deaths during a given time interval divided by the population.

\begin{figure}
\centering
\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/town-density-1.pdf}
\caption{\label{fig:town-density}Ridge plot of number of deaths in district by date}
\end{figure}

\hypertarget{what-were-the-mortality-rates-in-each-district}{%
\subsubsection{What were the mortality rates in each district?}\label{what-were-the-mortality-rates-in-each-district}}

\hypertarget{candidate-methods-for-assessing-excess-mortality.}{%
\paragraph{Candidate methods for assessing (excess) mortality.}\label{candidate-methods-for-assessing-excess-mortality.}}

A great benefit of the dataset at hand is the recording of a cause of death on the notice. This was either copied from the Certificate of the Medical Practitioner, or in the absence of such a certificate, told to the registrar by the informant. Hence, the most intuitive method to assess how many people died in each district of the Spanish flu is simply to count the number of deaths recorded with ``Spanish flu'' listed in the cause of death column. However, there are a number of drawbacks to this method.

\begin{itemize}
\tightlist
\item
  Doctors and families who reported to the registrar the cause of death may not have known that the deaths at the beginning of the pandemic were due to the Spanish flu as news of the disease likely travelled across the country slower than the disease itself.
\item
  There is likely some selection into the provision of a cause of death by location within a district. The Form of Information of a Death states that ``Medical Certificates are essential in Urban Areas,'' while in ``Rural Areas Informants can report in \textbf{three} ways -- one being under declaration'' (find correct citation for death notice).
\item
  There are discrepancies in the reporting of the disease by district. Contrast for instance the labelling of deaths in Cradock and Paarl. In the top facet of Figure \ref{fig:cradock-paarl-causes}, it is evident that the vast majority of deaths during the pandemic are labelled as Spanish flu deaths. In contrast, fewer than half of the deaths that occurred during the pandemic are labelled as Spanish flu deaths in Paarl.
\item
  To avoid this complication is is tempting to simply count the number of deaths in each district during the pandemic period and conclude that these were caused by the flu. However, districts of different population sizes would have expected different numbers of deaths in the absence of the pandemic. Hence it is not advisable to conclude that all recorded deaths were due to the flu.
\end{itemize}

\begin{figure}
\centering
\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/cradock-paarl-causes-1.pdf}
\caption{\label{fig:cradock-paarl-causes}Density plot comparing causes of death during the pandemic in Cradock and Paarl}
\end{figure}

Table \ref{tab:cradock-paarl-causes-tab} evidences that the majority of deaths in Paarl were labelled simply as ``Influenza.''

\begin{table}

\caption{\label{tab:cradock-paarl-causes-tab}Comparison of common causes of death in Cradock and Paarl during the pandemic}
\centering
\begin{tabular}[t]{l|r|l|r}
\hline
Cradock & n\_cradock & Paarl & n\_paarl\\
\hline
Spanish Influenza & 444 & Influenza & 367\\
\hline
Flu & 21 & Spanish Influenza & 247\\
\hline
Influenza & 20 & Pneumonia & 35\\
\hline
Bronchitis & 10 & Spanish Influenza, Pneumonia & 17\\
\hline
Broncho Pneumonia & 7 & Convulsions & 16\\
\hline
Convulsions & 6 & Spaanse Griep & 15\\
\hline
Teething & 5 & Spanish Influenza (Pneumonia) & 15\\
\hline
Diarrhoea & 3 & Bronchitis & 14\\
\hline
Old age & 3 & Broncho Pneumonia & 13\\
\hline
Consumption & 2 & Gastro Enteritis & 12\\
\hline
Inflammation of lungs & 2 & Spanish Flu & 12\\
\hline
Pneumonia & 2 & A) Spanish Influenza B) Pneumonia & 11\\
\hline
\end{tabular}
\end{table}

An alternate set of methods for quantifying excess mortality use history as a guide for the number of deaths that we can expect to occur in each district. These use the mortality figures for three years preceding the pandemic as a guide, looking at the average number of deaths in each district during the pandemic peak (October, November and December), taking an average of the whole year mortality in each district, and creating regression models with the historical data to predict the expected number of deaths in the pandemic period. I explain each below.

First, making use of the death notices from 1915 to 1917 and following the methodology laid out by the South Africa Medical Research Council in Dorrington et al. (2021), I calculate the average number of deaths per month in each town during the pandemic period in the three preceding years as a baseline. The SAMRC define excess mortality is calculated as ``the number of all-cause deaths in the last week less the number that might have been expected to have occurred'' (Dorrington et al. 2021, 2).

I then subtract this expected number of deaths from the observed number during the pandemic to calculate excess mortality.

The advantage of this method is that it captures the seasonal variation in

Problems: data too coarse to get reasonable estimates at district-week level. aggregate to district-month level.

\begin{figure}
\centering
\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/seasonality-1.pdf}
\caption{\label{fig:seasonality}Mortality by week across districts - excluding 1918}
\end{figure}

Second, I calculate a simple average of the number of deaths per year in each district in the three prior years. Table \ref{tab:mean-mortality-by-district-tab} shows the mortality by district from 1915 to 1917, and the average across these three years.

\begin{table}

\caption{\label{tab:mean-mortality-by-district-tab}Mortality by district in years preceding pandemic}
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
District & 1915 & 1916 & 1917 & Average\\
\hline
Queenstown & 843 & 1083 & 849 & 925\\
\hline
Oudtshoorn & 816 & 768 & 1019 & 868\\
\hline
Paarl & 731 & 715 & 755 & 734\\
\hline
Stellenbosch & 503 & 556 & 604 & 554\\
\hline
Cradock & 378 & 400 & 382 & 387\\
\hline
Mafeking & 344 & 382 & 344 & 357\\
\hline
Stockenstrom & 264 & 331 & 335 & 310\\
\hline
Komga & 241 & 338 & 301 & 293\\
\hline
Peddie & 266 & 264 & 270 & 267\\
\hline
Fraserburg & 244 & 230 & 192 & 222\\
\hline
Kuruman & 182 & 247 & 194 & 208\\
\hline
Riversdale & 199 & 203 & 204 & 202\\
\hline
Vryburg & 198 & 214 & 187 & 200\\
\hline
Elliot & 97 & 143 & 104 & 115\\
\hline
Sea Point & 19 & 43 & 70 & 44\\
\hline
\end{tabular}
\end{table}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-4-1.pdf}

Third, I use regression models to extrapolate the mortality we would expect in each district if the historical trends from 1915 to 1917 continued.

I use three regression models. These are linear model with only an intercept - in effect the same as the averaging procedure from above, but over a shorter window. Specifically, I average the number of deaths in the three month period including October, November and December in the three years prior to 1918 as a guide for the average number of deaths per district. This accounts for the seasonality shown in Figure \ref{fig:seasonality}, whereby there are a greater number of deaths in the second half of the year.

Next I use a simple linear regression. This accounts, for instance, for population growth and consequent linear increases in the number of registered deaths per district per year.

The linear trend is shown in the figure here:

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-5-1.pdf}

Further I use a regression model from Serfling that accounts for the seasonality of respiratory diseases like flu and influenza. ``Serfling's method uses cyclic regression to model the weekly proportion of deaths from pneumonia and influenza and to define an epidemic threshold that is adjusted for seasonal effects.'' (Cowling et al. 2006, 4).

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{table}

\caption{\label{tab:unnamed-chunk-7}Observed, predicted and excess mortality based on regression methods}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
District & Observed & Projected & Excess\\
\hline
Queenstown & 1693 & 886 & 807\\
\hline
Paarl & 1465 & 675 & 790\\
\hline
Peddie & 1048 & 259 & 789\\
\hline
Stockenstrom & 946 & 325 & 621\\
\hline
Stellenbosch & 1170 & 550 & 620\\
\hline
Komga & 827 & 283 & 544\\
\hline
Oudtshoorn & 1410 & 910 & 500\\
\hline
Mafeking & 781 & 332 & 449\\
\hline
Elliot & 527 & 112 & 415\\
\hline
Cradock & 763 & 364 & 399\\
\hline
Vryburg & 455 & 191 & 264\\
\hline
Kuruman & 427 & 220 & 207\\
\hline
Fraserburg & 264 & 178 & 86\\
\hline
Riversdale & 214 & 189 & 25\\
\hline
Sea Point & 54 & 51 & 3\\
\hline
\end{tabular}
\end{table}

\hypertarget{conclusion-of-excess-mortalty-calculations-is-to-use-all-respiratory-deaths-during-pandemic-as-pandemic-deaths---more-reliable-than-lsicing-data-in-preceding-years-thinly---due-to-data-coarsity.}{%
\subsubsection{Conclusion of excess mortalty calculations is to use all respiratory deaths during pandemic as pandemic deaths - more reliable than lsicing data in preceding years thinly - due to data coarsity.}\label{conclusion-of-excess-mortalty-calculations-is-to-use-all-respiratory-deaths-during-pandemic-as-pandemic-deaths---more-reliable-than-lsicing-data-in-preceding-years-thinly---due-to-data-coarsity.}}

A possible choice at this point would be to classify any death occurring during the pandemic with respiratory disease such as pneumonia or influenza listed in the cause of death as a Spanish flu death. {[}To be completed: In the appendix I show that this can be done effectively with a machine learning model and a relatively small set of hand-labelled training data.{]}

\hypertarget{timing-and-the-absence-of-subsequent-waves}{%
\paragraph{Timing and the absence of subsequent waves}\label{timing-and-the-absence-of-subsequent-waves}}

This speaks to the severity of the pandemic. Caveat, Komgha and Oudtshoorn.

\hypertarget{correlates}{%
\subsection{Correlates}\label{correlates}}

\hypertarget{pre-existing-health}{%
\subsubsection{Pre-existing health}\label{pre-existing-health}}

A wealth of literature has shown that there is a strong correlation between the level of health and prevalence of illnesses in different communities and their outcomes facing a pandemic.

I examine two measures of pre-existing health in the 15 districts which constitute the sample. The first uses infant and child mortality statistics as a proxy for the level of existing health and healthcare in a district. The second assess mortality from influenza and pneumonia prior to the pandemic to gauge levels of health in different communities.

\hypertarget{pre-pandemic-infant-and-child-mortality-rates}{%
\paragraph{Pre-pandemic infant and child mortality rates}\label{pre-pandemic-infant-and-child-mortality-rates}}

We start with infant mortality rates. Defined as the share of children below 1 dying each year divided by the number of births each year.

Two sources of data:
- infant deaths from our death notices in each district. Taken from 1915 - 1917.
- infant births - record from blue books/archive\ldots{} (CITAION). Multiply the snapshot by three to get an average mortality rate prior to the pandemic and make the most of the data at our disposal.

Infant mortality: deaths of those below children born in each town.

\begin{table}

\caption{\label{tab:unnamed-chunk-9}Infant mortality by race}
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
District & Aggregate & White & Black & Coloured\\
\hline
Stockenstrom & 346 & 130 & 448 & 221\\
\hline
Queenstown & 313 & 76 & 425 & NA\\
\hline
Cradock & 286 & 92 & 450 & 320\\
\hline
Elliot & 257 & 90 & 574 & NA\\
\hline
Oudtshoorn & 225 & 106 & NA & 320\\
\hline
Stellenbosch & 210 & 111 & NA & 243\\
\hline
Paarl & 203 & 69 & NA & 239\\
\hline
Mafeking & 190 & 96 & 223 & NA\\
\hline
Fraserburg & 178 & 85 & NA & 293\\
\hline
Komga & 169 & 48 & 180 & NA\\
\hline
Riversdale & 156 & 91 & NA & 220\\
\hline
Peddie & 144 & NA & 144 & NA\\
\hline
Kuruman & 132 & 66 & 165 & 204\\
\hline
Vryburg & 75 & 49 & 159 & 32\\
\hline
Sea Point & 17 & 11 & NA & 52\\
\hline
\end{tabular}
\end{table}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-10-1.pdf}

Now we know what the pre-existing infant mortality data looked like, we can examine how it was correlated with the pandemic mortality.

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-11-1.pdf}

{[}Conclude here{]}

\hypertarget{child-mortality}{%
\subparagraph{Child mortality}\label{child-mortality}}

Child mortality as a measure of pre-existing health in the different districts.

\begin{itemize}
\tightlist
\item
  Defined as the number of deaths in our death notice dataset, divided by the number of children below 5 years of age from census data. The denominator for white individuals is from the 1918 census, while for Black and Coloured individuals is from the 1911 census.
\end{itemize}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{table}

\caption{\label{tab:unnamed-chunk-13}Child mortality per 1000 recorded births}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
District & Aggregate & White & Black and Coloured\\
\hline
Vryburg & 67 & 79 & 65\\
\hline
Peddie & 73 & 50 & 74\\
\hline
Kuruman & 81 & 61 & 86\\
\hline
Elliot & 110 & 47 & 159\\
\hline
Mafeking & 118 & 126 & 117\\
\hline
Riversdale & 127 & 62 & 215\\
\hline
Komga & 160 & 42 & 174\\
\hline
Fraserburg & 175 & 81 & 291\\
\hline
Cradock & 180 & 62 & 232\\
\hline
Queenstown & 216 & 77 & 247\\
\hline
Oudtshoorn & 243 & 93 & 391\\
\hline
Paarl & 263 & 64 & 343\\
\hline
Stellenbosch & 270 & 108 & 340\\
\hline
Stockenstrom & 279 & 90 & 318\\
\hline
\end{tabular}
\end{table}

Now we can compare these mortality statistics during the pandemic

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-14-1.pdf}

Dependent variable:

mort\_rate

(1)

(2)

child\_mort\_rate

0.132***

0.066*

(0.030)

(0.038)

raceWhite

-0.020**

(0.008)

Constant

0.008

0.028***

(0.005)

(0.009)

Observations

28

28

R2

0.425

0.544

Adjusted R2

0.403

0.508

Residual Std. Error

0.017 (df = 26)

0.015 (df = 25)

F Statistic

19.243*** (df = 1; 26)

14.919*** (df = 2; 25)

Note:

\emph{p\textless0.1; \textbf{p\textless0.05; }}p\textless0.01

\hypertarget{pre-pandemic-pneumonia-and-influenza-mortality}{%
\paragraph{Pre-pandemic pneumonia and influenza mortality}\label{pre-pandemic-pneumonia-and-influenza-mortality}}

Acuña-Soto, Viboud, and Chowell (2011) show how influenza and pneumonia mortality prior to the pandemic are predictive of mortality rates during the pandemic in 66 large cities in the United States.

I follow their process here:

First I calculate the pre-pandemic mortality rates by district for influenza, pneumonia and both. These are shown in Table {[}cite{]} below.

\begin{table}

\caption{\label{tab:unnamed-chunk-16}Influenza and Pneumonia mortality per 1000 residents}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
District & Influenza & Pneumonia & Influenza and Pneumonia\\
\hline
Kuruman & 4.28 & 4.28 & 8.56\\
\hline
Riversdale & 3.18 & 5.76 & 8.94\\
\hline
Vryburg & 4.30 & 9.02 & 13.32\\
\hline
Peddie & 8.37 & 5.89 & 14.10\\
\hline
Mafeking & 0.49 & 14.77 & 15.26\\
\hline
Elliot & 7.28 & 11.79 & 18.72\\
\hline
Fraserburg & 5.21 & 20.85 & 26.06\\
\hline
Cradock & 2.31 & 23.84 & 26.15\\
\hline
Paarl & 0.79 & 27.82 & 28.61\\
\hline
Stellenbosch & 3.29 & 32.05 & 35.07\\
\hline
Queenstown & 8.02 & 29.17 & 37.02\\
\hline
Oudtshoorn & 1.95 & 42.89 & 44.59\\
\hline
Komga & 28.62 & 16.88 & 45.31\\
\hline
Stockenstrom & 22.65 & 75.60 & 98.25\\
\hline
\end{tabular}
\end{table}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-17-1.pdf}

While the individual slopes are lower, there is still a strong correlation between pre-existing pneumonia and influenza mortality rates and the pandemic mortality rate in each district.

Dependent variable:

pandemic\_mort\_rate

(1)

(2)

(3)

influenza\_mort

3.228**

(1.437)

pneumonia\_mort

1.370**

(0.511)

pneumonia\_influenza\_mort

1.481***

(0.431)

raceWhite

-0.023***

-0.019***

-0.015**

(0.007)

(0.007)

(0.007)

Constant

0.033***

0.029***

0.023***

(0.006)

(0.006)

(0.007)

Observations

26

28

28

R2

0.567

0.602

0.652

Adjusted R2

0.530

0.571

0.624

Residual Std. Error

0.015 (df = 23)

0.014 (df = 25)

0.013 (df = 25)

F Statistic

15.075*** (df = 2; 23)

18.945*** (df = 2; 25)

23.435*** (df = 2; 25)

Note:

\emph{p\textless0.1; \textbf{p\textless0.05; }}p\textless0.01

\hypertarget{literacy-proxy}{%
\paragraph{Literacy proxy}\label{literacy-proxy}}

I use a proxy for literacy of the individual's family to assess if literacy has an impact on how well residents of a district fare during the pandemic. The hypothesis is that districts with higher literacy rates will better adopt the best practices proposed by health authorities in an attempt to quell the pandemic and stop the spread of the disease.

Table {[}Cite{]} shows that there is considerable variation in our literacy proxy by district and race.

\begin{table}

\caption{\label{tab:unnamed-chunk-19}Percentage of district death notices wherein Informant signed}
\centering
\begin{tabular}[t]{l|l|l|l|l}
\hline
District & Aggregate & Black & Coloured & White\\
\hline
Fraserburg & 100\% & 100\% & 100\% & 100\%\\
\hline
Sea Point & 100\% & 100\% & 100\% & 100\%\\
\hline
Elliot & 99\% & 99\% & 100\% & 99\%\\
\hline
Stellenbosch & 49\% & 49\% & 37\% & 96\%\\
\hline
Paarl & 45\% & 46\% & 37\% & 94\%\\
\hline
Cradock & 45\% & 33\% & 36\% & 97\%\\
\hline
Vryburg & 45\% & 29\% & 30\% & 99\%\\
\hline
Riversdale & 43\% & 50\% & 15\% & 90\%\\
\hline
Mafeking & 42\% & 32\% & 51\% & 100\%\\
\hline
Queenstown & 40\% & 33\% & 30\% & 98\%\\
\hline
Oudtshoorn & 37\% & 27\% & 21\% & 90\%\\
\hline
Kuruman & 33\% & 16\% & 36\% & 96\%\\
\hline
Stockenstrom & 17\% & 7\% & 32\% & 93\%\\
\hline
Komga & 11\% & 6\% & 14\% & 95\%\\
\hline
Peddie & 9\% & 6\% & 20\% & 97\%\\
\hline
\end{tabular}
\end{table}

Figure {[}cite{]} shows the same thing.

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-20-1.pdf}

Is there an association between this proxy and the pandemic mortality rates?

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-21-1.pdf}

We can also test for statistical correlation:

Dependent variable:

mort\_rate

(1)

(2)

child\_mort\_rate

0.132***

0.066*

(0.030)

(0.038)

raceWhite

-0.020**

(0.008)

Constant

0.008

0.028***

(0.005)

(0.009)

Observations

28

28

R2

0.425

0.544

Adjusted R2

0.403

0.508

Residual Std. Error

0.017 (df = 26)

0.015 (df = 25)

F Statistic

19.243*** (df = 1; 26)

14.919*** (df = 2; 25)

Note:

\emph{p\textless0.1; \textbf{p\textless0.05; }}p\textless0.01

Here we observe the Yule-Simpson effect in practice, how exciting! This statistical effect occurs when a true effect is marked by failing to control for an additional variable. In this case, the best fit line for ``Both groups,'' shown in yellow, leads us to believe that as the proportion of our district with the literacy proxy increases, the pandemic mortality decreases, in line with our hypothesis. However, when we control for race, we see that the effect is not significant and the sign is in fact in the opposite direction, as visible in the blue and red lines in the figure.

\hypertarget{percentage-of-foriegn-born-individuals-and}{%
\paragraph{Percentage of foriegn born individuals and}\label{percentage-of-foriegn-born-individuals-and}}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-23-1.pdf}

Visual correlation.

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-24-1.pdf}

Statistical correlation

Dependent variable:

pandemic\_mort\_rate

share\_not\_cape

-0.032

(0.034)

Constant

0.032***

(0.006)

Observations

28

R2

0.032

Adjusted R2

-0.005

Residual Std. Error

0.022 (df = 26)

F Statistic

0.869 (df = 1; 26)

Note:

\emph{p\textless0.1; \textbf{p\textless0.05; }}p\textless0.01

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

\hypertarget{appendix}{%
\subsection{Appendix}\label{appendix}}

\hypertarget{linear-support-vector-machine-specification-and-workflow}{%
\subsubsection{Linear Support Vector Machine specification and workflow}\label{linear-support-vector-machine-specification-and-workflow}}

I use a linear support vector machine to classify ethnicity to race for black and coloured individuals based on a hand coded training set. I make use of sub-word features in my pre-processing tokenization. I use 10-fold cross validation in order to prevent data leakage and ensure that the classification results are robust.

\begin{verbatim}
## # A tibble: 6 x 2
##   race     ethnicity_as_recorded
##   <chr>    <chr>                
## 1 Black    Bechuana             
## 2 Coloured Cape Coloured        
## 3 Black    Kaffir               
## 4 Coloured Coloured             
## 5 Black    Kaffir               
## 6 Coloured Hottontot
\end{verbatim}

At outset I use my data budget by separating a training and assessment set from my labelled training set of 33,500 observations. This ensures that I can assess the performance of the model on data that it has not been trained on. The initial split uses 75 percent of the labelled data as training data and reserved 25 percent for testing. I also stratify the training and testing data based on race in order to ensure that the classes are as balanced as possible.

\begin{verbatim}
## <Analysis/Assess/Total>
## <25160/8388/33548>
\end{verbatim}

In an attempt to avoid overfitting on the training data, I create 10 folds of cross validation data. In essence I create 10 datasets that sample from the training data to tune my model parameters before testing the model performance on the testing data. Again I stratify by race in my folds.

\hypertarget{preprocessing-and-feature-engineering}{%
\paragraph{Preprocessing and feature engineering}\label{preprocessing-and-feature-engineering}}

Next I create a recipe for pre-processing and tokenizing the text prior to modelling.

I use the \texttt{textrecipes} package to tokenize the text into subword features. Using the \texttt{tokenizers.bpe} (where bpe stands for Byte-Pair Encoding) argument means that instead of breaking down our words into characters, the tokenizer algorithm will iteratively merge together frequently occurring subword pairs to find sub-words that are important in my dataset (Hvitfeldt and Silge 2021, 223). It is helpful in this case as we get a sweet spot between character level and word level information. Sub-word information like this is important in NLP models. Further, sub-word models can handle new/unknown words at prediction time, which bag of words models cannot.

I use the \texttt{themis} package to deal with class imbalance. The \texttt{step\_smote} argument generates new examples of the minority class using the nearest neighbours of those cases. In this case coloured is the minority class and as such the smote algorithm will create new examples of coloured observations with existing data from coloured observations.

\hypertarget{model-specification}{%
\paragraph{Model specification}\label{model-specification}}

\begin{verbatim}
## Linear Support Vector Machine Specification (classification)
## 
## Computational engine: LiblineaR
\end{verbatim}

\hypertarget{model-workflow}{%
\paragraph{Model workflow}\label{model-workflow}}

Here the workflow keeps together the pre-processor or recipe and the model specification.

\hypertarget{tuning-grid}{%
\paragraph{Tuning grid}\label{tuning-grid}}

The tuning grid specifies the values across which the model will search for the best performing number of tokens or predictors. The choices are specified manually in this case given the simple search space and single tuning parameter.

\hypertarget{tuning-parameters}{%
\paragraph{Tuning parameters}\label{tuning-parameters}}

By tuning the number of tokens using the 10 folds of cross validation data

\hypertarget{autoplot-results}{%
\paragraph{Autoplot results}\label{autoplot-results}}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-35-1.pdf}

\hypertarget{finalize-workflow}{%
\paragraph{Finalize workflow}\label{finalize-workflow}}

Here we will select the best model based on sensitivity.

\begin{verbatim}
## # A tibble: 3 x 4
##   .metric  .estimator .estimate .config             
##   <chr>    <chr>          <dbl> <chr>               
## 1 accuracy binary         0.998 Preprocessor1_Model1
## 2 sens     binary         0.999 Preprocessor1_Model1
## 3 spec     binary         0.997 Preprocessor1_Model1
\end{verbatim}

Wow!! 99.7 percent accuracy!

\hypertarget{confusion-matrix}{%
\paragraph{Confusion matrix}\label{confusion-matrix}}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-38-1.pdf}

\begin{verbatim}
## # A tibble: 101 x 2
##    term                               estimate
##    <chr>                                 <dbl>
##  1 tf_ethnicity_as_recorded_)         -0.00262
##  2 tf_ethnicity_as_recorded_,         -0.148  
##  3 tf_ethnicity_as_recorded_?          0.0284 
##  4 tf_ethnicity_as_recorded_<U+2581>          0.0519 
##  5 tf_ethnicity_as_recorded_<U+2581>(        -0.00302
##  6 tf_ethnicity_as_recorded_<U+2581>(Kaffir)  0.130  
##  7 tf_ethnicity_as_recorded_<U+2581>B        -0.109  
##  8 tf_ethnicity_as_recorded_<U+2581>Baralong  0.0679 
##  9 tf_ethnicity_as_recorded_<U+2581>Barolong  0.0654 
## 10 tf_ethnicity_as_recorded_<U+2581>Bast     -0.0626 
## # ... with 91 more rows
\end{verbatim}

\includegraphics{spanish-flu-mortality_bookdown_files/figure-latex/unnamed-chunk-39-1.pdf}

Here we can see that if the ethnicity contains the sub-word features ``KA,'' ``Z,''AT``,''OL``, and''AN``, the linear SVM is more likely to classify the individual as Black. In contrast, sub-word features''AR``, and''AM``,''M" and ``L'' are associated with coloured individuals.

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\hypertarget{ref-AcuaSoto2011InfluenzaAP}{}%
Acuña-Soto, R., C. Viboud, and G. Chowell. 2011. {``Influenza and Pneumonia Mortality in 66 Large Cities in the United States in Years Surrounding the 1918 Pandemic.''} \emph{PLoS ONE} 6.

\leavevmode\hypertarget{ref-Cowling2006}{}%
Cowling, Benjamin J, Irene O L Wong, Lai-Ming Ho, Steven Riley, and Gabriel M Leung. 2006. {``{Methods for monitoring influenza surveillance data}.''} \emph{International Journal of Epidemiology} 35 (5): 1314--21. \url{https://doi.org/10.1093/ije/dyl162}.

\leavevmode\hypertarget{ref-Dorrington2021}{}%
Dorrington, Rob, Debbie Bradshaw, Ria Laubscher, Pam Groenewald, and Tom Moultrie. 2021. {``{METHODOLOGICAL NOTE: PREDICTED NUMBERS OF DEATHS BY EPI-WEEK FOR SOUTH AFRICA IN 2020 AND 2021}.''} South African Medical Research Council. \url{https://www.samrc.ac.za/sites/default/files/files/2021-01-24/Methodological\%20Note\%20on\%20Predicted\%20Weekly\%20Deaths\%2020\%7B/_\%7DJan\%7B/_\%7D2021.pdf}.

\leavevmode\hypertarget{ref-FOURIE2021105407}{}%
Fourie, Johan, and Jonathan Jayes. 2021. {``Health Inequality and the 1918 Influenza in South Africa.''} \emph{World Development} 141: 105407. https://doi.org/\url{https://doi.org/10.1016/j.worlddev.2021.105407}.

\leavevmode\hypertarget{ref-hvitfeldt2021supervised}{}%
Hvitfeldt, E., and J. Silge. 2021. \emph{Supervised Machine Learning for Text Analysis in r}. Chapman \& Hall/CRC Data Science Series. Taylor \& Francis Limited. \url{https://books.google.co.za/books?id=WQ1qzgEACAAJ}.

\leavevmode\hypertarget{ref-Mtumane}{}%
Mtumane, Zilibele. 2017. {``The Practice of Ubuntu with Regard to amaMfengu Among amaXhosa as Depicted in s. E. K. Mqhayi's Ityala Lamawele.''} \emph{International Journal of African Renaissance Studies - Multi-, Inter- and Transdisciplinarity} 12 (2): 68--80. \url{https://doi.org/10.1080/18186874.2017.1392146}.

\leavevmode\hypertarget{ref-Stapleton}{}%
Stapleton, Timothy J. 1995. {``Oral Evidence in a Pseudo-Ethnicity: The Fingo Debate.''} \emph{History in Africa} 22: 359--68. \url{http://www.jstor.org/stable/3171922}.

\leavevmode\hypertarget{ref-Suthaharan2016}{}%
Suthaharan, Shan. 2016. {``Support Vector Machine.''} In \emph{Machine Learning Models and Algorithms for Big Data Classification: Thinking with Examples for Effective Learning}, 207--35. Boston, MA: Springer US. \url{https://doi.org/10.1007/978-1-4899-7641-3_9}.

\end{CSLReferences}



\end{document}
